#line 1 "_quad.c.src"

/*
 *****************************************************************************
 **       This file was autogenerated from a template  DO NOT EDIT!!!!      **
 **       Changes should be made to the original source (.src) file         **
 *****************************************************************************
 */

#line 1
/* #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION */

#include <Python.h>
#include <stddef.h>
#include <quadmath.h>

#include <numpy/arrayobject.h>
#include <numpy/ufuncobject.h>

#include "pyquad.h"
#include "number.h"

PyArray_ArrFuncs NpyQuad_ArrFuncs;

typedef struct { char c; qdouble q; } align_test;

PyArray_Descr npyquad_descr = {
    PyObject_HEAD_INIT(0)
    &PyQuad_Type,       /* typeobj */
    'f',                /* kind */
    'q',                /* type */
    '=',                /* byteorder */
    /*
     * For now, we need NPY_NEEDS_PYAPI in order to make numpy detect our
     * exceptions.  This isn't technically necessary,
     * since we're careful about thread safety, and hopefully future
     * versions of numpy will recognize that.
     */
    NPY_NEEDS_PYAPI | NPY_USE_GETITEM | NPY_USE_SETITEM, /* hasobject */
    0,                      /* type_num */
    sizeof(qdouble),       /* elsize */
    offsetof(align_test, q), /* alignment */
    0,                      /* subarray */
    0,                      /* fields */
    0,                      /* names */
    &NpyQuad_ArrFuncs,  /* f */
    0,                      /* metadata */
    0,
};

static PyObject *
npyquad_getitem(char *data, PyArrayObject *NPY_UNUSED(arr))
{
    qdouble q;

    memcpy(&q, data, sizeof(q));
    return PyQuad_FromQuad(q);
}

static int
npyquad_setitem(PyObject *item, void *data, void *NPY_UNUSED(arr))
{
    qdouble q;

    if (PyQuad_Check(item)) {
        q = ((PyQuad*)item)->obval;
        memcpy(data, &q, sizeof(q));
        return 0;
    } else  {
        PyErr_Format(PyExc_TypeError,
                "%s: expected qdouble, got %s", __func__, item->ob_type->tp_name);
        return -1;
    }
}

static void
byteswap(qdouble* x)
{
    size_t n = sizeof(qdouble), i;
    union swapped {
        qdouble* value;
        char* data;
    } s = {x};
    char tmp;

    for (i = 0; i < n; ++i) {
        tmp = s.data[i];
        s.data[i] = s.data[n - i -1];
        s.data[n - i - 1] = tmp;
    }
}

static void
npyquad_copyswap(void* dst, void* src, int swap, void* NPY_UNUSED(arr))
{
    qdouble *q;

    if (!src) {
        return;
    }
    q = (qdouble*)dst;
    /* FIXME: memmove vs memcpy */
    memmove(q, src, sizeof(*q));
    if (swap) {
        byteswap(q);
    }
}

#line 104
static void
npycast_int8_to_quad(void* from, void* to, npy_intp n, void* NPY_UNUSED(fromarr), void* NPY_UNUSED(toarr))
{
    const npy_int8 *typed_from = (npy_int8*)from;
    qdouble *typed_to = (qdouble*)to;
    npy_intp i;

    for (i = 0; i < n; i++) {
        typed_to[i] = (qdouble)typed_from[i];
    }
}

static int register_int8_to_qdouble_cast(int npy_registered_quadnum)
{
    PyArray_Descr* from_descr = PyArray_DescrFromType(NPY_INT8);
    int safe = 1;

    if (PyArray_RegisterCastFunc(from_descr, npy_registered_quadnum, npycast_int8_to_quad) < 0) {
        return -1;
    }
    if (safe && PyArray_RegisterCanCast(from_descr, npy_registered_quadnum, NPY_NOSCALAR) < 0) {
        return -1;
    }

    return 0;
}

#line 104
static void
npycast_int16_to_quad(void* from, void* to, npy_intp n, void* NPY_UNUSED(fromarr), void* NPY_UNUSED(toarr))
{
    const npy_int16 *typed_from = (npy_int16*)from;
    qdouble *typed_to = (qdouble*)to;
    npy_intp i;

    for (i = 0; i < n; i++) {
        typed_to[i] = (qdouble)typed_from[i];
    }
}

static int register_int16_to_qdouble_cast(int npy_registered_quadnum)
{
    PyArray_Descr* from_descr = PyArray_DescrFromType(NPY_INT16);
    int safe = 1;

    if (PyArray_RegisterCastFunc(from_descr, npy_registered_quadnum, npycast_int16_to_quad) < 0) {
        return -1;
    }
    if (safe && PyArray_RegisterCanCast(from_descr, npy_registered_quadnum, NPY_NOSCALAR) < 0) {
        return -1;
    }

    return 0;
}

#line 104
static void
npycast_int32_to_quad(void* from, void* to, npy_intp n, void* NPY_UNUSED(fromarr), void* NPY_UNUSED(toarr))
{
    const npy_int32 *typed_from = (npy_int32*)from;
    qdouble *typed_to = (qdouble*)to;
    npy_intp i;

    for (i = 0; i < n; i++) {
        typed_to[i] = (qdouble)typed_from[i];
    }
}

static int register_int32_to_qdouble_cast(int npy_registered_quadnum)
{
    PyArray_Descr* from_descr = PyArray_DescrFromType(NPY_INT32);
    int safe = 1;

    if (PyArray_RegisterCastFunc(from_descr, npy_registered_quadnum, npycast_int32_to_quad) < 0) {
        return -1;
    }
    if (safe && PyArray_RegisterCanCast(from_descr, npy_registered_quadnum, NPY_NOSCALAR) < 0) {
        return -1;
    }

    return 0;
}

#line 104
static void
npycast_int64_to_quad(void* from, void* to, npy_intp n, void* NPY_UNUSED(fromarr), void* NPY_UNUSED(toarr))
{
    const npy_int64 *typed_from = (npy_int64*)from;
    qdouble *typed_to = (qdouble*)to;
    npy_intp i;

    for (i = 0; i < n; i++) {
        typed_to[i] = (qdouble)typed_from[i];
    }
}

static int register_int64_to_qdouble_cast(int npy_registered_quadnum)
{
    PyArray_Descr* from_descr = PyArray_DescrFromType(NPY_INT64);
    int safe = 1;

    if (PyArray_RegisterCastFunc(from_descr, npy_registered_quadnum, npycast_int64_to_quad) < 0) {
        return -1;
    }
    if (safe && PyArray_RegisterCanCast(from_descr, npy_registered_quadnum, NPY_NOSCALAR) < 0) {
        return -1;
    }

    return 0;
}

#line 104
static void
npycast_float_to_quad(void* from, void* to, npy_intp n, void* NPY_UNUSED(fromarr), void* NPY_UNUSED(toarr))
{
    const float *typed_from = (float*)from;
    qdouble *typed_to = (qdouble*)to;
    npy_intp i;

    for (i = 0; i < n; i++) {
        typed_to[i] = (qdouble)typed_from[i];
    }
}

static int register_float_to_qdouble_cast(int npy_registered_quadnum)
{
    PyArray_Descr* from_descr = PyArray_DescrFromType(NPY_FLOAT);
    int safe = 1;

    if (PyArray_RegisterCastFunc(from_descr, npy_registered_quadnum, npycast_float_to_quad) < 0) {
        return -1;
    }
    if (safe && PyArray_RegisterCanCast(from_descr, npy_registered_quadnum, NPY_NOSCALAR) < 0) {
        return -1;
    }

    return 0;
}

#line 104
static void
npycast_double_to_quad(void* from, void* to, npy_intp n, void* NPY_UNUSED(fromarr), void* NPY_UNUSED(toarr))
{
    const double *typed_from = (double*)from;
    qdouble *typed_to = (qdouble*)to;
    npy_intp i;

    for (i = 0; i < n; i++) {
        typed_to[i] = (qdouble)typed_from[i];
    }
}

static int register_double_to_qdouble_cast(int npy_registered_quadnum)
{
    PyArray_Descr* from_descr = PyArray_DescrFromType(NPY_DOUBLE);
    int safe = 1;

    if (PyArray_RegisterCastFunc(from_descr, npy_registered_quadnum, npycast_double_to_quad) < 0) {
        return -1;
    }
    if (safe && PyArray_RegisterCanCast(from_descr, npy_registered_quadnum, NPY_NOSCALAR) < 0) {
        return -1;
    }

    return 0;
}

#line 104
static void
npycast_ldouble_to_quad(void* from, void* to, npy_intp n, void* NPY_UNUSED(fromarr), void* NPY_UNUSED(toarr))
{
    const long double *typed_from = (long double*)from;
    qdouble *typed_to = (qdouble*)to;
    npy_intp i;

    for (i = 0; i < n; i++) {
        typed_to[i] = (qdouble)typed_from[i];
    }
}

static int register_ldouble_to_qdouble_cast(int npy_registered_quadnum)
{
    PyArray_Descr* from_descr = PyArray_DescrFromType(NPY_LONGDOUBLE);
    int safe = 1;

    if (PyArray_RegisterCastFunc(from_descr, npy_registered_quadnum, npycast_ldouble_to_quad) < 0) {
        return -1;
    }
    if (safe && PyArray_RegisterCanCast(from_descr, npy_registered_quadnum, NPY_NOSCALAR) < 0) {
        return -1;
    }

    return 0;
}


#line 136
static void
npycast_quad_to_int8(void* from, void* to, npy_intp n, void* NPY_UNUSED(fromarr), void* NPY_UNUSED(toarr))
{
    const qdouble *typed_from = (qdouble*)from;
    npy_int8 *typed_to = (npy_int8*)to;
    npy_intp i;

    for (i = 0; i < n; i++) {
        typed_to[i] = (npy_int8)typed_from[i];
    }
}

static int register_qdouble_to_int8_cast(int npy_registered_quadnum)
{
    PyArray_Descr* from_descr = &npyquad_descr;

    if (PyArray_RegisterCastFunc(from_descr, npy_registered_quadnum, npycast_quad_to_int8) < 0) {
        return -1;
    }

    return 0;
}

#line 136
static void
npycast_quad_to_int16(void* from, void* to, npy_intp n, void* NPY_UNUSED(fromarr), void* NPY_UNUSED(toarr))
{
    const qdouble *typed_from = (qdouble*)from;
    npy_int16 *typed_to = (npy_int16*)to;
    npy_intp i;

    for (i = 0; i < n; i++) {
        typed_to[i] = (npy_int16)typed_from[i];
    }
}

static int register_qdouble_to_int16_cast(int npy_registered_quadnum)
{
    PyArray_Descr* from_descr = &npyquad_descr;

    if (PyArray_RegisterCastFunc(from_descr, npy_registered_quadnum, npycast_quad_to_int16) < 0) {
        return -1;
    }

    return 0;
}

#line 136
static void
npycast_quad_to_int32(void* from, void* to, npy_intp n, void* NPY_UNUSED(fromarr), void* NPY_UNUSED(toarr))
{
    const qdouble *typed_from = (qdouble*)from;
    npy_int32 *typed_to = (npy_int32*)to;
    npy_intp i;

    for (i = 0; i < n; i++) {
        typed_to[i] = (npy_int32)typed_from[i];
    }
}

static int register_qdouble_to_int32_cast(int npy_registered_quadnum)
{
    PyArray_Descr* from_descr = &npyquad_descr;

    if (PyArray_RegisterCastFunc(from_descr, npy_registered_quadnum, npycast_quad_to_int32) < 0) {
        return -1;
    }

    return 0;
}

#line 136
static void
npycast_quad_to_int64(void* from, void* to, npy_intp n, void* NPY_UNUSED(fromarr), void* NPY_UNUSED(toarr))
{
    const qdouble *typed_from = (qdouble*)from;
    npy_int64 *typed_to = (npy_int64*)to;
    npy_intp i;

    for (i = 0; i < n; i++) {
        typed_to[i] = (npy_int64)typed_from[i];
    }
}

static int register_qdouble_to_int64_cast(int npy_registered_quadnum)
{
    PyArray_Descr* from_descr = &npyquad_descr;

    if (PyArray_RegisterCastFunc(from_descr, npy_registered_quadnum, npycast_quad_to_int64) < 0) {
        return -1;
    }

    return 0;
}

#line 136
static void
npycast_quad_to_float(void* from, void* to, npy_intp n, void* NPY_UNUSED(fromarr), void* NPY_UNUSED(toarr))
{
    const qdouble *typed_from = (qdouble*)from;
    float *typed_to = (float*)to;
    npy_intp i;

    for (i = 0; i < n; i++) {
        typed_to[i] = (float)typed_from[i];
    }
}

static int register_qdouble_to_float_cast(int npy_registered_quadnum)
{
    PyArray_Descr* from_descr = &npyquad_descr;

    if (PyArray_RegisterCastFunc(from_descr, npy_registered_quadnum, npycast_quad_to_float) < 0) {
        return -1;
    }

    return 0;
}

#line 136
static void
npycast_quad_to_double(void* from, void* to, npy_intp n, void* NPY_UNUSED(fromarr), void* NPY_UNUSED(toarr))
{
    const qdouble *typed_from = (qdouble*)from;
    double *typed_to = (double*)to;
    npy_intp i;

    for (i = 0; i < n; i++) {
        typed_to[i] = (double)typed_from[i];
    }
}

static int register_qdouble_to_double_cast(int npy_registered_quadnum)
{
    PyArray_Descr* from_descr = &npyquad_descr;

    if (PyArray_RegisterCastFunc(from_descr, npy_registered_quadnum, npycast_quad_to_double) < 0) {
        return -1;
    }

    return 0;
}

#line 136
static void
npycast_quad_to_ldouble(void* from, void* to, npy_intp n, void* NPY_UNUSED(fromarr), void* NPY_UNUSED(toarr))
{
    const qdouble *typed_from = (qdouble*)from;
    long double *typed_to = (long double*)to;
    npy_intp i;

    for (i = 0; i < n; i++) {
        typed_to[i] = (long double)typed_from[i];
    }
}

static int register_qdouble_to_ldouble_cast(int npy_registered_quadnum)
{
    PyArray_Descr* from_descr = &npyquad_descr;

    if (PyArray_RegisterCastFunc(from_descr, npy_registered_quadnum, npycast_quad_to_ldouble) < 0) {
        return -1;
    }

    return 0;
}


static int register_cast_functions(int npy_registered_quadnum)
{
#line 165
    if(register_int8_to_qdouble_cast(npy_registered_quadnum) < 0) {
        return -1;
    }
    if(register_qdouble_to_int8_cast(npy_registered_quadnum) < 0) {
        return -1;
    }

#line 165
    if(register_int16_to_qdouble_cast(npy_registered_quadnum) < 0) {
        return -1;
    }
    if(register_qdouble_to_int16_cast(npy_registered_quadnum) < 0) {
        return -1;
    }

#line 165
    if(register_int32_to_qdouble_cast(npy_registered_quadnum) < 0) {
        return -1;
    }
    if(register_qdouble_to_int32_cast(npy_registered_quadnum) < 0) {
        return -1;
    }

#line 165
    if(register_int64_to_qdouble_cast(npy_registered_quadnum) < 0) {
        return -1;
    }
    if(register_qdouble_to_int64_cast(npy_registered_quadnum) < 0) {
        return -1;
    }

#line 165
    if(register_float_to_qdouble_cast(npy_registered_quadnum) < 0) {
        return -1;
    }
    if(register_qdouble_to_float_cast(npy_registered_quadnum) < 0) {
        return -1;
    }

#line 165
    if(register_double_to_qdouble_cast(npy_registered_quadnum) < 0) {
        return -1;
    }
    if(register_qdouble_to_double_cast(npy_registered_quadnum) < 0) {
        return -1;
    }

#line 165
    if(register_ldouble_to_qdouble_cast(npy_registered_quadnum) < 0) {
        return -1;
    }
    if(register_qdouble_to_ldouble_cast(npy_registered_quadnum) < 0) {
        return -1;
    }

    return 0;
}

void
init_quad_descriptor(PyObject* np_module)
{
    int npy_registered_quadnum;

    PyArray_InitArrFuncs(&NpyQuad_ArrFuncs);
    NpyQuad_ArrFuncs.getitem = (PyArray_GetItemFunc*)npyquad_getitem;
    NpyQuad_ArrFuncs.setitem = (PyArray_SetItemFunc*)npyquad_setitem;
    NpyQuad_ArrFuncs.copyswap = (PyArray_CopySwapFunc*)npyquad_copyswap;

    npyquad_descr.ob_type = &PyArrayDescr_Type;
    npy_registered_quadnum = PyArray_RegisterDataType(&npyquad_descr);
    if (npy_registered_quadnum < 0) {
        return;
    }

    /* Support dtype(qdouble) syntax */
    if (PyDict_SetItemString(PyQuad_Type.tp_dict, "dtype",
			     (PyObject*)&npyquad_descr) < 0) {
        return;
    }

    if (register_cast_functions(npy_registered_quadnum) < 0) {
        return;
    }
}


/*
 * Module initialization boilerplate
 */
static PyMethodDef ModuleMethods[] = {
    {NULL, NULL, 0, NULL}
};


PyMODINIT_FUNC init_quad(void)
{
    PyObject *m;
    PyObject *np_module;
    PyObject *s;

    import_array();
    if (PyErr_Occurred()) {
        return;
    }
    import_umath();
    if (PyErr_Occurred()) {
        return;
    }

    s = PyString_FromString("numpy");
    if (!s) {
        return;
    }
    np_module = PyImport_Import(s);
    Py_DECREF(s);

    m = Py_InitModule("_quad", ModuleMethods);
    if (m == NULL) {
        return;
    }
    init_quad_type(m, &PyGenericArrType_Type);

    init_quad_descriptor(np_module);
}

